### ISSUE TITLE
Create a post on the Benefits of Open Data

### ISSUE THREAD

**Issue by hunvreus** [Wiredcraft/marketing-dashboard#2]
We need to prepare a post for the [Wiredcraft Blog](www.wiredcraft.com/blog)
- You can find some notes and research I have prepared for this post in this hackpad. Feel free to work directly in this hackpad. 
  https://wiredcraft.hackpad.com/Benefits-of-Open-Data-H3YUT8n0BDV
- You can check our post about how to write a post here: http://wiredcraft.com/blog/blogging-in-3-steps/. Feel free to ignore this.

Here are some posts on our blog to help give you an idea of our direction. 

http://wiredcraft.com/blog/data-visualizations-images/
http://wiredcraft.com/blog/bringing-the-world-bank-data-to-sub-national-levels/
http://wiredcraft.com/blog/how-we-design-products/
http://wiredcraft.com/blog/toa-shenjs/

You can take inspiration from Development Seed:

https://developmentseed.org/blog/unhcr-redesign-relaunch/
https://developmentseed.org/blog/2015/04/15/openstreetmap-for-government/
https://developmentseed.org/blog/2015/04/14/tracking-osm-metadata/
https://developmentseed.org/blog/2014/10/01/mexico-open-data-push/
https://developmentseed.org/blog/2014/09/19/global-resilience-partnership-launch/
https://developmentseed.org/blog/2013/08/01/mapping-affordable-care-act/
https://developmentseed.org/blog/2013/10/24/its-called-jekyll/

Remember that we are trying to reach out to people that are interested in the international development community. You can start by dumping your ideas in a hackpad and start organizing the key points.

For an illustration reach out to @erqiudao through github or slack. As discussed you can leave messages for me here or reach out on slack. 

Overly communicating is never a problem.

**Comment by haquesaurus** [comment]
Completed. Closing
