### ISSUE TITLE
Create a Blog Post, Edit a few paragraphs, Make a plan for marketing & hosting Design Meetup

### ISSUE THREAD

**Issue by Katierichard** [Wiredcraft/marketing-dashboard#3]
Thank you for interviewing with us. For the next step we will have you preform the following tasks; we do this so we can see how you work with our team and learn a bit more about your creative process. 
1. Edit the paragraphs in [this document](https://wiredcraft.hackpad.com/Editing-Task-h9yEk2xKPg3). 
2. List the steps that you’d take to plan and market our next [Design Meetup](http://www.meetup.com/Shanghai-UI-UX-Designers-Meetup/) You can do the planning in [hackpad](https://wiredcraft.hackpad.com/Meetup-Plan-and-Marketing-z1yR35EF7iW).
3. Please prepare a post for the Wiredcraft Blog in English. You can choose one of the following topics, or create your own. 
   - Best practices for marketing on wechat or weibo/
   - Best practices for marketing to the Chinese market

You can do all your planning and writing in [Hackpad](https://wiredcraft.hackpad.com/Blog-Post-Hackpad-RdeSsiVnM2w)

Check our post about how to write a blog post here: http://wiredcraft.com/blog/blogging-in-3-steps/ or feel free to ignore this.

For an illustration reach out to @Iriszhousy or @hazelyang through github or slack. As discussed you can leave messages for me or @audreyhaque  here or reach out on slack.

Overly communicating is never a problem. Please reach out to @audreyhaque or I on github or slack if you have any questions.

**Comment by haquesaurus** [comment]
Closing.
